# Generated by Django 2.2.5 on 2019-10-14 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='ratio',
            new_name='rating',
        ),
    ]
